before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  -
    id: headless
    binary: netclient
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm_5
      - linux_arm_6
      - linux_arm_7
      - linux_mips_hardfloat
      - linux_mips_softfloat
      - linux_mipsle_softfloat
      - linux_mipsle_hardfloat
      - windows_amd64
      - darwin_amd64
      - darwin_arm64

archives:
  - format: binary
    name_template: '{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}-{{ . }}{{ end }}'
release:
  prerelease: false
