FROM gravitl/go-builder:1.23.0 as builder
WORKDIR /app
COPY . .
RUN GOOS=linux CGO_ENABLED=0 /usr/local/go/bin/go build -ldflags="-w -s" -o netclient-app .

FROM alpine:3.21.0

WORKDIR /root/

RUN apk add --no-cache wireguard-tools iproute2 openrc net-tools curl \
    && mkdir -p /run/openrc \
    && touch /run/openrc/softlevel
RUN curl -L -o /usr/local/bin/wireguard-go https://github.com/WireGuard/wireguard-go/releases/latest/download/wireguard-go && \
    chmod +x /usr/local/bin/wireguard-go
RUN apk add iptables ip6tables \
    && cp -v /usr/sbin/ip6tables-nft /sbin/ip6tables
COPY --from=builder /app/netclient-app ./netclient
COPY --from=builder /app/scripts/netclient.sh .
RUN chmod 0755 netclient && chmod 0755 netclient.sh

ENV WG_QUICK_USERSPACE_IMPLEMENTATION=wireguard-go

ENTRYPOINT ["/bin/bash", "./netclient.sh"]
