FROM gravitl/go-builder:1.23.0 as builder
WORKDIR /app
COPY . .
RUN GOOS=linux CGO_ENABLED=0 /usr/local/go/bin/go build -ldflags="-w -s" -o netclient-app .

FROM alpine:3.21.0

WORKDIR /root/

RUN apk add --no-cache "net-tools"
RUN mkdir -p /dev/net \
mknod /dev/net/tun c 10 200 \
chmod 600 /dev/net/tun
RUN apk add --no-cache --update bash libmnl gcompat openresolv iproute2 wireguard-tools openrc \
    && mkdir -p /run/openrc \
    && touch /run/openrc/softlevel
RUN apk add iptables ip6tables \
    && cp -v /usr/sbin/ip6tables-nft /sbin/ip6tables
COPY --from=builder /app/netclient-app ./netclient
COPY --from=builder /app/scripts/netclient.sh .
RUN chmod 0755 netclient && chmod 0755 netclient.sh

ENV WG_QUICK_USERSPACE_IMPLEMENTATION=wireguard-go

ENTRYPOINT ["/bin/bash", "./netclient.sh"]
