FROM gravitl/go-builder:latest as builder
# add glib support daemon manager
WORKDIR /app


ENV GO111MODULE=auto
RUN apk add --update git build-base libmnl-dev iptables libpcap-dev
COPY . .

RUN GOOS=linux CGO_ENABLED=1 /usr/local/go/bin/go build -tags headless -ldflags="-w -s" -o netclient-app .

FROM alpine:3.16.2

WORKDIR /root/

RUN apk add --no-cache --update bash libmnl gcompat iptables openresolv iproute2 libpcap
COPY --from=builder /app/netclient-app ./netclient
COPY --from=builder /app/scripts/netclient.sh .
RUN chmod 0755 netclient && chmod 0755 netclient.sh

ENV WG_QUICK_USERSPACE_IMPLEMENTATION=wireguard-go

ENTRYPOINT ["/bin/bash", "./netclient.sh"]
