// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';
import {wgtypes} from '../models';
import {frontend} from '../models';
import {models} from '../models';

export function GoConnectToNetwork(arg1:string):Promise<any>;

export function GoDisconnectFromNetwork(arg1:string):Promise<any>;

export function GoGetKnownNetworks():Promise<Array<main.Network>>;

export function GoGetNetclientConfig():Promise<main.NcConfig>;

export function GoGetNetwork(arg1:string):Promise<main.Network>;

export function GoGetNodePeers(arg1:config.Node):Promise<Array<wgtypes.PeerConfig>>;

export function GoGetRecentServerNames():Promise<Array<string>>;

export function GoJoinNetworkByToken(arg1:string):Promise<any>;

export function GoLeaveNetwork(arg1:string):Promise<any>;

export function GoOpenDialogue(arg1:frontend.DialogType,arg2:string,arg3:string):Promise<string>;

export function GoParseAccessToken(arg1:string):Promise<models.AccessToken>;

export function GoPullLatestNodeConfig(arg1:string):Promise<main.Network>;

export function GoRegisterWithEnrollmentKey(arg1:string):Promise<any>;

export function GoUninstall():Promise<any>;

export function GoUpdateNetclientConfig(arg1:config.Config):Promise<any>;

export function GoWriteToClipboard(arg1:string):Promise<any>;
