// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoConnectToNetwork(arg1) {
  return window['go']['main']['App']['GoConnectToNetwork'](arg1);
}

export function GoDisconnectFromNetwork(arg1) {
  return window['go']['main']['App']['GoDisconnectFromNetwork'](arg1);
}

export function GoGetKnownNetworks() {
  return window['go']['main']['App']['GoGetKnownNetworks']();
}

export function GoGetNetclientConfig() {
  return window['go']['main']['App']['GoGetNetclientConfig']();
}

export function GoGetNetwork(arg1) {
  return window['go']['main']['App']['GoGetNetwork'](arg1);
}

export function GoGetNodePeers(arg1) {
  return window['go']['main']['App']['GoGetNodePeers'](arg1);
}

export function GoGetRecentServerNames() {
  return window['go']['main']['App']['GoGetRecentServerNames']();
}

export function GoGetStatus() {
  return window['go']['main']['App']['GoGetStatus']();
}

export function GoJoinNetworkByBasicAuth(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GoJoinNetworkByBasicAuth'](arg1, arg2, arg3, arg4);
}

export function GoJoinNetworkBySso(arg1, arg2) {
  return window['go']['main']['App']['GoJoinNetworkBySso'](arg1, arg2);
}

export function GoLeaveNetwork(arg1) {
  return window['go']['main']['App']['GoLeaveNetwork'](arg1);
}

export function GoOpenDialogue(arg1, arg2, arg3) {
  return window['go']['main']['App']['GoOpenDialogue'](arg1, arg2, arg3);
}

export function GoPullLatestNodeConfig(arg1) {
  return window['go']['main']['App']['GoPullLatestNodeConfig'](arg1);
}

export function GoRegisterWithEnrollmentKey(arg1) {
  return window['go']['main']['App']['GoRegisterWithEnrollmentKey'](arg1);
}

export function GoUninstall() {
  return window['go']['main']['App']['GoUninstall']();
}

export function GoUpdateNetclientConfig(arg1) {
  return window['go']['main']['App']['GoUpdateNetclientConfig'](arg1);
}

export function GoWriteToClipboard(arg1) {
  return window['go']['main']['App']['GoWriteToClipboard'](arg1);
}
