// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoConnectToNetwork(arg1) {
  return window['go']['main']['App']['GoConnectToNetwork'](arg1);
}

export function GoDisconnectFromNetwork(arg1) {
  return window['go']['main']['App']['GoDisconnectFromNetwork'](arg1);
}

export function GoGetKnownNetworks() {
  return window['go']['main']['App']['GoGetKnownNetworks']();
}

export function GoGetNetclientConfig() {
  return window['go']['main']['App']['GoGetNetclientConfig']();
}

export function GoGetNetwork(arg1) {
  return window['go']['main']['App']['GoGetNetwork'](arg1);
}

export function GoJoinNetworkByToken(arg1) {
  return window['go']['main']['App']['GoJoinNetworkByToken'](arg1);
}

export function GoLeaveNetwork(arg1) {
  return window['go']['main']['App']['GoLeaveNetwork'](arg1);
}

export function GoParseAccessToken(arg1) {
  return window['go']['main']['App']['GoParseAccessToken'](arg1);
}
