package config

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"net"
	"os"
	"strings"
)

const (
	resolvconfFile       = "/etc/resolv.conf"
	resolvconfBackupFile = "/etc/netmaker-resolv.backup.conf"
)

type fileManager struct{}

func newFileManager() (*fileManager, error) {
	return &fileManager{}, nil
}

func (f *fileManager) Configure(config Config) error {
	if len(config.Nameservers) == 0 {
		if !f.ownedByUs() {
			return nil
		}

		return f.resetConfig()
	}

	if !f.ownedByUs() {
		err := os.Rename(resolvconfFile, resolvconfBackupFile)
		if err != nil {
			return err
		}
	}

	return f.writeConfig(config.Nameservers, config.SearchDomains)
}

func (f *fileManager) ownedByUs() bool {
	conf, err := os.Open(resolvconfFile)
	if err != nil {
		return false
	}
	defer func() {
		_ = conf.Close()
	}()

	scanner := bufio.NewScanner(conf)
	for scanner.Scan() {
		if strings.HasPrefix(scanner.Text(), "# resolv.conf(5) file generated by netmaker") {
			return true
		} else {
			return false
		}
	}

	return false
}

func (f *fileManager) writeConfig(nameservers []net.IP, searchDomains []string) error {
	conf, err := os.Create(resolvconfFile)
	if err != nil {
		return err
	}
	defer func() {
		_ = conf.Close()
	}()

	confBytes := new(bytes.Buffer)

	writeConfig(confBytes, nameservers, searchDomains)

	_, err = conf.Write(confBytes.Bytes())
	return err
}

func (f *fileManager) resetConfig() error {
	return os.Rename(resolvconfBackupFile, resolvconfFile)
}

func (f *fileManager) SupportsInterfaceSpecificConfig() bool {
	return false
}

func writeConfig(confBytes io.StringWriter, nameservers []net.IP, searchDomains []string) {
	_, _ = confBytes.WriteString("# resolv.conf(5) file generated by netmaker\n")
	_, _ = confBytes.WriteString("# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN\n\n")
	for _, nameserver := range nameservers {
		_, _ = confBytes.WriteString(fmt.Sprintf("nameserver %s\n", nameserver.String()))
	}

	if len(searchDomains) > 0 {
		_, _ = confBytes.WriteString(fmt.Sprintf("search %s\n", strings.Join(searchDomains, " ")))
	}
}
