package config

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"net"
	"os"
	"strings"
	"sync"
)

const (
	resolvconfFile       = "/etc/resolv.conf"
	resolvconfBackupFile = "/etc/netmaker-resolv.backup.conf"
)

type fileManager struct {
	configs map[string]Config
	mu      sync.Mutex
}

func newFileManager(opts ...ManagerOption) (*fileManager, error) {
	f := &fileManager{
		configs: make(map[string]Config),
	}
	var options ManagerOptions
	for _, opt := range opts {
		opt(&options)
	}

	if options.cleanupResidual && f.ownedByUs() {
		err := f.resetConfig()
		if err != nil {
			return nil, err
		}
	}

	return f, nil
}

func (f *fileManager) Configure(iface string, config Config) error {
	if iface == "" {
		return fmt.Errorf("interface name is required")
	}

	f.mu.Lock()
	defer f.mu.Unlock()

	if config.Remove {
		if !f.ownedByUs() {
			return nil
		}

		delete(f.configs, iface)
	} else {
		f.configs[iface] = config
	}

	if !f.ownedByUs() {
		err := os.Rename(resolvconfFile, resolvconfBackupFile)
		if err != nil {
			return err
		}
	}

	var nameservers []net.IP
	var searchDomains []string
	nameserversMap := make(map[string]bool)
	searchDomainsMap := make(map[string]bool)
	for _, config := range f.configs {
		for _, nameserver := range config.Nameservers {
			_, ok := nameserversMap[nameserver.String()]
			if !ok {
				nameserversMap[nameserver.String()] = true
				nameservers = append(nameservers, nameserver)
			}
		}

		for _, domain := range config.SearchDomains {
			_, ok := searchDomainsMap[domain]
			if !ok {
				searchDomainsMap[domain] = true
				searchDomains = append(searchDomains, domain)
			}
		}
	}

	return f.writeConfig(nameservers, searchDomains)
}

func (f *fileManager) ownedByUs() bool {
	conf, err := os.Open(resolvconfFile)
	if err != nil {
		return false
	}
	defer func() {
		_ = conf.Close()
	}()

	scanner := bufio.NewScanner(conf)
	for scanner.Scan() {
		if strings.HasPrefix(scanner.Text(), "# resolv.conf(5) file generated by netmaker") {
			return true
		} else {
			return false
		}
	}

	return false
}

func (f *fileManager) writeConfig(nameservers []net.IP, searchDomains []string) error {
	confBytes := new(bytes.Buffer)

	writeConfig(confBytes, nameservers, searchDomains)

	oldConf, err := os.Open(resolvconfBackupFile)
	if err != nil {
		return err
	}
	defer func() {
		_ = oldConf.Close()
	}()

	scanner := bufio.NewScanner(oldConf)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		confBytes.WriteString(line + "\n")
	}

	return os.WriteFile(resolvconfFile, confBytes.Bytes(), 0644)
}

func (f *fileManager) resetConfig() error {
	return os.Rename(resolvconfBackupFile, resolvconfFile)
}

func writeConfig(confBytes io.StringWriter, nameservers []net.IP, searchDomains []string) {
	_, _ = confBytes.WriteString("# resolv.conf(5) file generated by netmaker\n")
	_, _ = confBytes.WriteString("# DO NOT EDIT THIS FILE BY HAND -- CHANGES WILL BE OVERWRITTEN\n\n")
	for _, nameserver := range nameservers {
		_, _ = confBytes.WriteString(fmt.Sprintf("nameserver %s\n", nameserver.String()))
	}

	if len(searchDomains) > 0 {
		_, _ = confBytes.WriteString(fmt.Sprintf("search %s\n", strings.Join(searchDomains, " ")))
	}
}
