package config

import (
	"bufio"
	"bytes"
	"fmt"
	"net"
	"os"
	"os/exec"
	"strings"
	"sync"
)

const (
	globalResolvconfFile       = "/etc/resolvconf/resolv.conf.d/head"
	globalResolvconfBackupFile = "/etc/resolvconf/resolv.conf.d/head.backup.conf"
)

type resolvconfManager struct {
	globalResolvers map[string]Config
	mu              sync.Mutex
}

func newResolvconfManager(opts ...ManagerOption) (*resolvconfManager, error) {
	r := &resolvconfManager{}
	var options ManagerOptions
	for _, opt := range opts {
		opt(&options)
	}

	if options.cleanupResidual {
		for _, iface := range options.residualInterfaces {
			err := r.resetConfig(iface)
			if err != nil {
				return nil, fmt.Errorf("failed to cleanup config for interface (%s): %v", iface, err)
			}
		}
	}

	return r, nil
}

func (r *resolvconfManager) Configure(iface string, config Config) error {
	if iface == "" {
		return fmt.Errorf("interface name is required")
	}

	r.mu.Lock()
	defer r.mu.Unlock()

	if config.Remove {
		return r.resetConfig(iface)
	}

	if !config.SplitDNS {
		r.globalResolvers[iface] = config

		if !r.globalResolvconfOwnedByUs() {
			err := os.Rename(globalResolvconfFile, globalResolvconfBackupFile)
			if err != nil {
				return err
			}
		}

		return r.writeGlobalResolvconfConfig()
	} else {
		confBytes := new(bytes.Buffer)

		writeConfig(confBytes, config.Nameservers, config.SearchDomains)

		cmd := exec.Command("resolvconf", "-a", iface)
		cmd.Stdin = confBytes
		return cmd.Run()
	}
}

func (r *resolvconfManager) resetConfig(iface string) error {
	_, ok := r.globalResolvers[iface]
	if ok {
		delete(r.globalResolvers, iface)

		if r.globalResolvconfOwnedByUs() {
			if len(r.globalResolvers) == 0 {
				return os.Rename(globalResolvconfBackupFile, globalResolvconfFile)
			} else {
				return r.writeGlobalResolvconfConfig()
			}
		} else {
			// global resolv.conf is not owned by us, so can't clear anything.
			// resetting global resolver config.
			r.globalResolvers = make(map[string]Config)
			return nil
		}
	} else {
		return exec.Command("resolvconf", "-d", iface).Run()
	}
}

func (r *resolvconfManager) globalResolvconfOwnedByUs() bool {
	conf, err := os.Open(globalResolvconfFile)
	if err != nil {
		return false
	}
	defer func() {
		_ = conf.Close()
	}()

	scanner := bufio.NewScanner(conf)
	for scanner.Scan() {
		if strings.HasPrefix(scanner.Text(), "# resolv.conf(5) file generated by netmaker") {
			return true
		} else {
			return false
		}
	}

	return false
}

func (r *resolvconfManager) writeGlobalResolvconfConfig() error {
	confBytes := new(bytes.Buffer)

	var nameservers []net.IP
	var searchDomains []string
	nameserversMap := make(map[string]bool)
	searchDomainsMap := make(map[string]bool)
	for _, config := range r.globalResolvers {
		for _, nameserver := range config.Nameservers {
			_, ok := nameserversMap[nameserver.String()]
			if !ok {
				nameserversMap[nameserver.String()] = true
				nameservers = append(nameservers, nameserver)
			}
		}

		for _, searchDomain := range config.MatchDomains {
			_, ok := searchDomainsMap[searchDomain]
			if !ok {
				searchDomainsMap[searchDomain] = true
				searchDomains = append(searchDomains, searchDomain)
			}
		}
	}

	writeConfig(confBytes, nameservers, searchDomains)

	return os.WriteFile(globalResolvconfFile, confBytes.Bytes(), 0644)
}
