package config

import (
	"bufio"
	"bytes"
	"fmt"
	"net"
	"os"
	"os/exec"
	"strings"
)

const (
	globalResolvconfFile       = "/etc/resolvconf/resolv.conf.d/head"
	globalResolvconfBackupFile = "/etc/resolvconf/resolv.conf.d/head.backup.conf"
)

type resolvconfManager struct {
	globalResolvers map[string]Config
}

func newResolvconfManager(opts ...ManagerOption) (*resolvconfManager, error) {
	r := &resolvconfManager{}
	var options ManagerOptions
	for _, opt := range opts {
		opt(&options)
	}

	if options.cleanupResidual {
		for _, iface := range options.residualInterfaces {
			err := r.resetConfig(iface)
			if err != nil {
				// TODO: suppress iface does not exist
				return nil, fmt.Errorf("failed to cleanup config for interface (%s): %v", iface, err)
			}

			if r.globalResolvconfOwnedByUs() {
				err := os.Rename(globalResolvconfBackupFile, globalResolvconfFile)
				if err != nil {
					return nil, fmt.Errorf("failed to cleanup global resolvconf config: %v", err)
				}
			}
		}
	}

	return r, nil
}

func (r *resolvconfManager) Configure(iface string, config Config) error {
	if iface == "" {
		return fmt.Errorf("interface name is required")
	}

	if config.Remove {
		return r.resetConfig(iface)
	}

	if !config.SplitDNS {
		r.globalResolvers[iface] = config

		confBytes := new(bytes.Buffer)

		var nameservers []net.IP
		var searchDomains []string
		for _, config := range r.globalResolvers {
			nameservers = append(nameservers, config.Nameservers...)
			searchDomains = append(searchDomains, config.SearchDomains...)
		}

		writeConfig(confBytes, nameservers, searchDomains)

		err := os.Rename(globalResolvconfFile, globalResolvconfBackupFile)
		if err != nil {
			return err
		}

		err = os.WriteFile(globalResolvconfFile, confBytes.Bytes(), 0644)
		if err != nil {
			return err
		}

	} else {
		confBytes := new(bytes.Buffer)

		searchDomains := make([]string, len(config.SearchDomains))
		for i, domain := range config.SearchDomains {
			if domain != "." {
				searchDomains[i] = domain
			}
		}

		writeConfig(confBytes, config.Nameservers, searchDomains)

		cmd := exec.Command("resolvconf", "-a", iface)
		cmd.Stdin = confBytes
		return cmd.Run()
	}

	return nil
}

func (r *resolvconfManager) resetConfig(iface string) error {
	_, ok := r.globalResolvers[iface]
	if ok {
		err := os.Rename(globalResolvconfBackupFile, globalResolvconfFile)
		if err != nil {
			return err
		}

		delete(r.globalResolvers, iface)
	} else {
		return exec.Command("resolvconf", "-d", iface).Run()
	}

	return nil
}

func (r *resolvconfManager) globalResolvconfOwnedByUs() bool {
	conf, err := os.Open(globalResolvconfFile)
	if err != nil {
		return false
	}
	defer func() {
		_ = conf.Close()
	}()

	scanner := bufio.NewScanner(conf)
	for scanner.Scan() {
		if strings.HasPrefix(scanner.Text(), "# resolv.conf(5) file generated by netmaker") {
			return true
		} else {
			return false
		}
	}

	return false
}
