name: Deploy and Test Branch

on:
  pull_request:
      types: [opened, synchronize, reopened]
      branches: [develop]

jobs:
  skip-check:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.skip.outputs.skip }}
    steps:
      - id: skip
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'always'

  getbranch:
    runs-on: ubuntu-latest
    needs: skip-check
    if: ${{ needs.skip-check.outputs.skip != 'true' }}
    outputs:
      netmakerbranch: ${{ steps.getbranch.outputs.netmakerbranch }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: gravitl/netmaker
          ref: develop
      - name: check if branch exists
        id: getbranch
        run: |
          if git show-ref ${{ github.head_ref}}; then
            echo branch exists
            echo "netmakerbranch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo branch does not exist
            echo "netmakerbranch=develop" >> $GITHUB_OUTPUT
          fi
  
  branchtest:
    uses: gravitl/devops/.github/workflows/testdeploybranch.yml@master
    needs: [getbranch, skip-check]
    with:
      netmakerbranch: ${{ needs.getbranch.outputs.netmakerbranch }}
      netclientbranch: ${{ github.head_ref }}
      tag: ${{ github.run_id }}-${{ github.run_attempt }}
    secrets: inherit