name: Pre-Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true

jobs:
  release:
    uses: gravitl/devops/.github/workflows/netclientPrerelease.yml@master
    with:
      version: ${{ inputs.version }}
    secrets: inherit
