name: Publish Netclient-Userspace Docker

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'docker tag'
        required: true

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64, linux/arm/v7
          file: ./Dockerfile-netclient-multiarch-userspace
          push: true
          tags: |
            gravitl/netclient-go:${{ github.event.inputs.tag }}
            gravitl/netclient-go:latest
